export const INVOICE_FETCH_REQUEST = "INVOICE_FETCH_REQUEST";
export const INVOICE_FETCH_SUCCESS = "INVOICE_FETCH_SUCCESS";
export const INVOICE_FETCH_FAIL = "INVOICE_FETCH_FAIL";

export const PAYMENT_ADD_REQUEST = "PAYMENT_ADD_REQUEST";
export const PAYMENT_ADD_SUCCESS = "PAYMENT_ADD_SUCCESS";
export const PAYMENT_ADD_FAIL = "PAYMENT_ADD_FAIL";

export const INVOICE_ARCHIVE_REQUEST = "INVOICE_ARCHIVE_REQUEST";
export const INVOICE_ARCHIVE_SUCCESS = "INVOICE_ARCHIVE_SUCCESS";
export const INVOICE_ARCHIVE_FAIL = "INVOICE_ARCHIVE_FAIL";

export const INVOICE_RESTORE_REQUEST = "INVOICE_RESTORE_REQUEST";
export const INVOICE_RESTORE_SUCCESS = "INVOICE_RESTORE_SUCCESS";
export const INVOICE_RESTORE_FAIL = "INVOICE_RESTORE_FAIL";

// Invoice List
export const INVOICE_LIST_REQUEST = "INVOICE_LIST_REQUEST";
export const INVOICE_LIST_SUCCESS = "INVOICE_LIST_SUCCESS";
export const INVOICE_LIST_FAIL = "INVOICE_LIST_FAIL";

// ------------------------
// Create Invoice
// ------------------------
export const INVOICE_CREATE_REQUEST = "INVOICE_CREATE_REQUEST";
export const INVOICE_CREATE_SUCCESS = "INVOICE_CREATE_SUCCESS";
export const INVOICE_CREATE_FAIL = "INVOICE_CREATE_FAIL";

export const DELETE_INVOICE_REQUEST = "DELETE_INVOICE_REQUEST";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";

